version: '3.5'
services:
  shopping_cart:
    build: .
    restart: always
    ports:
      - 8001:8000
    depends_on:
      shopping-cart-db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - host

  shopping-cart-db:
    image: postgres:14.1-alpine
    ports:
      - 5437:5432
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - cart_data:/var/lib/postgresql/data
    restart: always

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - host
    # this second PostgresSQL is used when running test
  shopping-cart-db-test:
    image: postgres:14.1-alpine
    ports:
      - 5438:5432
    environment:
      POSTGRES_DB: shopping-cart
      POSTGRES_USER: shopping-cart
      POSTGRES_PASSWORD: shopping-cart
  zookeeper:
    image: zookeeper:3.6.2
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  kafka-consumer:
    image: wurstmeister/kafka:2.13-2.8.1
    command: bash -c "mkdir -vp /tmp/kafka-logs && /opt/kafka_2.13-2.8.1/bin/kafk-console-consumer.sh --zookeeper zookeeper:2181 --from-beginning --topic-name > /tmp/kafka-logs/topic-name.log"
    ports:
      - "9094:9092"
    links:
      - zookeeper
      - kafka
    volumes:
      - ./kafka-1-logs:/tmp/kafka-logs

  wait-for-kafka:
    image: waisbrot/wait
    links:
      - kafka
    environment:
      - TARGETS=kafka:9092

volumes:
  cart_data:


networks:
  host:
